### ISSUE TITLE
Update accuracy metric in recursive_feature_machine.py (pip version)

### ISSUE THREAD

**Issue by ro-mish** [aradha/recursive_feature_machines#1]
For pip version. 
Score function for accuracy is currently using argmax, which fails when targets are of dimensions (n,1).

**Comment by parthe** [comment]
Can you create a pull request?

**Comment by parthe** [comment]
can you add a line that uses `torchmetrics.functional`? we can add that as a dependency.

**Comment by parthe** [comment]
created a pull request from OP
