### ISSUE TITLE
M doesn't get updated when self.diag is true, does it?

### ISSUE THREAD

**Issue by seyedparsa** [aradha/recursive_feature_machines#3]
Shouldn't this line start with `self.M =` to store the returned value of `einsum` in self.M?
https://github.com/aradha/recursive_feature_machines/blob/a89c96e4dc729415f19ffad732c080a4d84f0752/rfm/recursive_feature_machine.py#L175

**Comment by parthe** [comment]
Fixed in commit `ad9bdf5`
